[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "aind_ephys_utils"
description = "Helpful methods for exploring in vivo electrophysiology data"
license = {text = "MIT"}
requires-python = ">=3.9"
authors = [
    {name = "Allen Institute for Neural Dynamics"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
readme = "README.md"
dynamic = ["version"]

dependencies = [
    'xarray',
    'scikit-learn',
    'ipympl'
]

[project.optional-dependencies]
dev = [
    'polars',
    'black',
    'coverage',
    'flake8',
    'interrogate',
    'isort',
    'Sphinx',
    'furo'
]

[tool.setuptools]
license-files = ["LICENSE", "THIRD_PARTY_LICENSES.md"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "aind_ephys_utils.__version__"}

[tool.black]
line-length = 79
target_version = ['py39']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
    | code
    | environment
    | data
    | metadata
    | results
    | scratch
  )/
  | .gitignore
)
'''

[tool.coverage.run]
omit = ["*__init__*"]
source = ["aind_ephys_utils", "tests"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
fail_under = 40

[tool.isort]
line_length = 90
profile = "black"
src_paths = ["src", "tests"]

[tool.interrogate]
exclude = ["setup.py", 
           "docs", 
           "build", 
           "code", 
           "environment",
           "metadata",
           "results",
           "data",
           "notebooks",
           "scratch"]
fail-under = 100
