name: Tag and publish
on:
  push:
    branches:
      - main
jobs:
  tag:
    uses: AllenNeuralDynamics/aind-github-actions/.github/workflows/tag.yml@main
    secrets:
      SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
  publish:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest changes
        run: git pull origin main
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install --upgrade setuptools wheel twine build
          python -m build
          twine check dist/*
      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.AIND_PYPI_TOKEN }}
  build-docs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      # Step 3: Install dependencies (including Sphinx)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      
      # Step 4: Build the documentation
      - name: Build Documentation
        run: |
          sphinx-apidoc -f -e -H "API" -o docs/source/api src/aind_ephys_utils
          sphinx-build -b html docs/source docs/build/html
        # Fail the workflow if documentation build fails
        continue-on-error: false
